# Generated by Django 4.2 on 2023-06-26 05:25

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areaconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_area', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name_areaconocimiento', message='No cumple con el estandar. Ej: A01', regex='^[aA]\\d{2}$')], verbose_name='Código')),
                ('nombre_area', models.CharField(max_length=20, verbose_name='Nombre')),
                ('desc_area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('cod_area_contenida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.areaconocimiento', verbose_name='Código sub área')),
            ],
            options={
                'verbose_name_plural': 'Áreas de conocimiento',
                'db_table': 'areaconocimiento',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_autor', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('primer_nombre', models.CharField(max_length=40, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=40, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo apellido')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_editorial', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('nombre_editorial', models.CharField(max_length=30, verbose_name='Nombre')),
                ('pagina_web', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('pais_origen', models.CharField(blank=True, max_length=30, null=True, verbose_name='País origen')),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
                'db_table': 'editorial',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('anio_publicacion', models.IntegerField(blank=True, null=True, verbose_name='Año publicación')),
                ('numero_pagina', models.IntegerField(blank=True, null=True, verbose_name='Número de páginas')),
                ('autores', models.ManyToManyField(to='app.autor')),
                ('codigo_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.areaconocimiento', verbose_name='Area de conocimiento')),
                ('codigo_editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion solicitud')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Libros descargados',
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='LibroDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=30, verbose_name='Formato')),
                ('url', models.URLField(verbose_name='URL')),
                ('tamanio', models.IntegerField(verbose_name='Tamaño del Libro')),
                ('libro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name_plural': 'Libros digitales',
                'db_table': 'libro_digital',
            },
        ),
        migrations.CreateModel(
            name='Descargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateField(default=datetime.datetime.now)),
                ('direccion_ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.librodigital', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Libros descargados',
                'db_table': 'descargas_libros',
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ejemplar', models.PositiveIntegerField(verbose_name='Número ejemplar')),
                ('numero_sala', models.PositiveIntegerField(verbose_name='Número de sala')),
                ('numero_pasillo', models.PositiveIntegerField(verbose_name='Número de pasillo')),
                ('numero_estante', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de estante')),
                ('numero_cajon', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de cajón')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name_plural': 'Ejemplares',
                'db_table': 'ejemplar',
                'unique_together': {('libro', 'numero_ejemplar')},
            },
        ),
    ]
