# Generated by Django 4.2 on 2023-06-26 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_descargas_fecha_descarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 7, 51, 5, 871720), verbose_name='Fecha de devolucion'),
        ),
    ]
