# Generated by Django 4.2 on 2023-06-26 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_prestamo_fecha_devolucion_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 8, 59, 23, 753504), verbose_name='Fecha de devolucion'),
        ),
    ]
