# Generated by Django 4.2 on 2023-06-26 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_multa_estado_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='valor',
            field=models.IntegerField(blank=True, default=1200, null=True, verbose_name='Valor multa'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 9, 22, 52, 886737), verbose_name='Fecha de devolucion'),
        ),
    ]
