# Generated by Django 4.2 on 2023-06-26 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_multa_valor_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 9, 31, 25, 518390), verbose_name='Fecha de devolucion'),
        ),
    ]
