# Generated by Django 4.2 on 2023-06-26 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 9, 39, 33, 76106), verbose_name='Fecha de devolucion'),
        ),
    ]
