# Generated by Django 4.2 on 2023-06-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacion'),
        ),
    ]
